sudo: false
language: node_js
node_js:
#  - "4"
  - "5"
#before_script:
#  - export DISPLAY=:99.0
#  - sh -e /etc/init.d/xvfb start


before_install:
#  - gem update # optional, update all gems
#  - gem install selenium-webdriver
  - phantomjs --version



addons:
  firefox: latest
  apt:
    sources:
     - google-chrome
    packages:
     - google-chrome-stable fluxbox


before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3
  - fluxbox >/dev/null 2>&1 &

 # - "npm install -g bower"
 # - "npm install -g phantomjs"
 # - "mysql -e 'create database jksdjksdjdjks;'"
 # - "cp ./config/database.travis.yml ./config/database.yml"
 # - "RAILS_ENV=test bundle exec rake db:migrate"
 # - "bundle exec rake bower:install"
